import {useEffect, useRef, useState, type CSSProperties} from 'react';
import {ArrowLeft, ArrowRight, ArrowUpRight, ChevronDown, Copy, Download, Flag, Plus, RefreshCw, Save, Search, Trophy} from 'lucide-react';
import {api, type Player, type Tournament, type User} from './api';
import TournamentView from './TournamentView';
import {tournamentPath} from './routes';
import {BadgeEditor, TeamMark, type BadgeMap} from './TeamBadges';
import PlayerMultiSelect from './PlayerMultiSelect';

type Kind='finali'|'svizzero';
type Entry={id:string;name:string;mode?:'ko'|'groups';finished:boolean;rounds?:number};
type Match={index:number;round:number;round_name?:string;home:string;away:string;home_goals:number;away_goals:number;valid:boolean;winner?:string};
type Standing={Squadra:string;Punti:number;G:number;V:number;N:number;P:number;GF:number;GS:number;DR:number;Potenziale:number};
type Competition={id:string;name:string;version:string;matches:Match[];active_round:number;finished:boolean;winner?:string;standings?:Standing[];participants?:{Giocatore:string;Squadra:string;Potenziale:number}[];byes?:{team:string;round:number}[];mode?:string;max_rounds?:number;badges?:BadgeMap};
type Source={id:string;name:string;ranking:{team:string;points:number;difference:number;gf:number}[]};
type Draft={home:number;away:number;valid:boolean};
type ViewMode='compact'|'premium'|'standard';
const err=(e:unknown)=>e instanceof Error?e.message:'Operazione non riuscita.';
const format=(name:string,mode:string)=>{if(mode==='complete')return name;const sep=name.includes(' - ')?' - ':'-';const i=name.indexOf(sep);return i<0?name:mode==='teams'?name.slice(0,i).trim():name.slice(i+sep.length).trim();};
const title=(name:string)=>{const clean=name.replace(/^finito_/, '');return clean.startsWith('fasefinaleEliminazionediretta_')?'Eliminazione diretta · '+clean.slice('fasefinaleEliminazionediretta_'.length):clean.startsWith('fasefinaleAGironi_')?'Fase a gironi · '+clean.slice('fasefinaleAGironi_'.length):clean;};

export default function CompetitionArea({kind,user,canWrite,directName,onDirty,onLegacy}:{kind:Kind;user:User;canWrite:boolean;directName:string;onDirty:(v:boolean)=>void;onLegacy:()=>void}){
  const [entries,setEntries]=useState<Entry[]>([]);const [sources,setSources]=useState<Source[]>([]);const [selected,setSelected]=useState<Competition|Tournament|null>(null);const [selectedMode,setSelectedMode]=useState<'ko'|'groups'|'swiss'>('swiss');
  const [creating,setCreating]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [search,setSearch]=useState('');
  const base=kind==='finali'?'/finals':'/swiss';
  const refresh=()=>api<Entry[]>(base).then(setEntries).catch(e=>setError(err(e)));
  useEffect(()=>{void refresh();if(kind==='finali')api<Source[]>('/finals/sources').then(setSources).catch(e=>setError(err(e)));},[kind]);
  const attempted=useRef('');
  useEffect(()=>{if(!directName){setSelected(null);attempted.current='';}},[directName]);
  useEffect(()=>{if(directName&&entries.length&&attempted.current!==directName){attempted.current=directName;const found=entries.filter(e=>e.name===directName);if(found.length===1)void open(found[0],true);else setError(found.length?'Il nome del torneo non è univoco.':'Torneo non trovato.');}},[directName,entries]);
  async function open(entry:Entry,replace=false){setBusy(true);setError('');try{const mode=kind==='svizzero'?'swiss':entry.mode!;const data=await api<Competition|Tournament>((mode==='groups'?'/tournaments':base)+'/'+entry.id);setSelected(data);setSelectedMode(mode);window.history[replace?'replaceState':'pushState']({},'',tournamentPath(entry.name,kind));}catch(e){setError(err(e));}finally{setBusy(false);}}
  function back(){onDirty(false);setSelected(null);window.history.pushState({},'',`/${kind}`);void refresh();}
  const writable=canWrite&&(!selected?.name.includes('Campionato')||user.role==='A');
  if(selected&&selectedMode==='groups')return <TournamentView tournament={selected as Tournament} user={user} canWrite={canWrite} onBack={back} onSaved={value=>{setSelected(value);window.history.replaceState({},'',tournamentPath(value.name,kind));void refresh();}} onDirty={onDirty} onLegacy={onLegacy} onFinali={back} routeType="finali"/>;
  if(selected)return <CompetitionView key={selected.id} kind={kind} data={selected as Competition} writable={writable} user={user} onBack={back} onSaved={value=>{setSelected(value);window.history.replaceState({},'',tournamentPath(value.name,kind));void refresh();}} onDirty={onDirty} onLegacy={onLegacy}/>;
  return <>
    <section className="page-heading"><div><div className="eyebrow">TIGULLIO CLUB · COMPETIZIONI</div><h1>{kind==='finali'?'🏆 Fasi finali':'✚ Torneo svizzero'}</h1><p>{kind==='finali'?'Dai qualificati al trofeo: gironi o eliminazione diretta.':'Ogni turno apre nuovi incroci, guidati dalla classifica.'}</p></div>{canWrite&&<button className="primary" onClick={()=>setCreating(true)}><Plus size={18}/>Nuovo torneo</button>}</section>
    {error&&<div className="alert error" role="alert">{error}</div>}
    {creating&&(kind==='finali'?<FinalsCreate sources={sources} onClose={()=>setCreating(false)} onCreated={async id=>{setCreating(false);await refresh();const entry=(await api<Entry[]>(base)).find(e=>e.id===id);if(entry)await open(entry);}}/>:<SwissCreate onClose={()=>setCreating(false)} onCreated={async id=>{setCreating(false);await refresh();const entry=(await api<Entry[]>(base)).find(e=>e.id===id);if(entry)await open(entry);}}/>)}
    <section className="archive"><div className="section-heading"><div><h2>{kind==='finali'?'Tabelloni e gironi':'Archivio svizzero'}</h2><p>Apri una competizione e riprendi dall’ultimo turno.</p></div><label className="search"><Search size={17}/><input aria-label="Cerca torneo" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cerca un torneo…"/></label></div>
      <div className="tournament-list">{entries.filter(e=>e.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(entry=><button key={entry.id} className="tournament-row" disabled={busy} onClick={()=>void open(entry)}><span className="tournament-icon">{kind==='finali'?<Flag/>:<Trophy/>}</span><span className="tournament-title"><strong>{title(entry.name)}</strong><small>{entry.mode==='ko'?'Eliminazione diretta':entry.mode==='groups'?'Fase a gironi':`Turno ${entry.rounds||1}`}</small></span><span className={'badge '+(entry.finished?'done':'')}>{entry.finished?'Concluso':'In corso'}</span><ArrowRight size={18}/></button>)}{entries.length===0&&<div className="empty"><Trophy/><h3>Il primo torneo ti aspetta</h3><p>{canWrite?'Crea la competizione per iniziare.':'I tornei disponibili compariranno qui.'}</p></div>}</div></section>
    <div className="legacy-note"><span>La versione classica resta disponibile durante la migrazione.</span><button className="text-button" onClick={onLegacy}>Apri versione classica<ArrowUpRight size={15}/></button></div>
  </>;
}

function FinalsCreate({sources,onClose,onCreated}:{sources:Source[];onClose:()=>void;onCreated:(id:string)=>void}){
  const [sourceId,setSourceId]=useState(sources[0]?.id||'');const [mode,setMode]=useState<'ko'|'groups'>('ko');const [qualifiers,setQualifiers]=useState(4);const [groupCount,setGroupCount]=useState(1);const [returnMatches,setReturnMatches]=useState(false);const [manual,setManual]=useState(false);const [assign,setAssign]=useState<Record<string,number>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const requestId=useRef(crypto.randomUUID());
  useEffect(()=>{if(!sourceId&&sources[0])setSourceId(sources[0].id);},[sources]);
  const source=sources.find(x=>x.id===sourceId);const selected=source?.ranking.slice(0,qualifiers)||[];const groups=Array.from({length:groupCount},(_,i)=>selected.filter((_,n)=>(assign[selected[n].team]??n%groupCount)===i).map(r=>r.team));
  const valid=!!source&&qualifiers<=source.ranking.length&&(mode==='ko'?qualifiers>=2&&(qualifiers&(qualifiers-1))===0&&qualifiers<=32:qualifiers>=4&&groupCount<=Math.floor(qualifiers/4)&&(!manual||groups.every(g=>g.length>=4)));
  async function submit(){setBusy(true);setError('');try{const response=await api<{id:string}>('/finals','POST',{source_id:sourceId,mode,qualifiers,group_count:groupCount,return_matches:returnMatches,groups:mode==='groups'&&manual?groups:null,request_id:requestId.current});onCreated(response.id);}catch(e){setError(err(e));}finally{setBusy(false);}}
  return <section className="results-card competition-create"><div className="section-heading"><div><h2>✨ Crea fase finale</h2><p>Parti da un preliminare completato, senza modificarlo.</p></div></div>{error&&<div className="alert error">{error}</div>}{!sources.length?<p>Nessun preliminare completato disponibile.</p>:<><div className="creation-options"><label>Torneo preliminare<select value={sourceId} onChange={e=>setSourceId(e.target.value)}>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Formato<select value={mode} onChange={e=>setMode(e.target.value as 'ko'|'groups')}><option value="ko">⚡ Eliminazione diretta</option><option value="groups">🏆 Fase a gironi</option></select></label><label>Qualificati<input type="number" min={2} max={Math.min(64,source?.ranking.length||64)} value={qualifiers} onChange={e=>setQualifiers(Number(e.target.value))}/></label>{mode==='groups'&&<><label>Numero di gironi<input type="number" min={1} max={8} value={groupCount} onChange={e=>setGroupCount(Number(e.target.value))}/></label><label>Calendario<select value={returnMatches?'return':'single'} onChange={e=>setReturnMatches(e.target.value==='return')}><option value="single">Solo andata</option><option value="return">Andata e ritorno</option></select></label>{groupCount>1&&<label className="checkbox"><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)}/>Assegnazione manuale</label>}</>}</div><div className="group-preview">{mode==='groups'&&groupCount>1&&manual?selected.map((row,i)=><label key={row.team}>{i+1}. {row.team}<select value={assign[row.team]??i%groupCount} onChange={e=>setAssign(a=>({...a,[row.team]:Number(e.target.value)}))}>{groups.map((_,g)=><option key={g} value={g}>Girone {g+1}</option>)}</select></label>):selected.map((row,i)=><div key={row.team}>{i+1}. {row.team} <small>· {row.points} punti</small></div>)}</div>{mode==='ko'&&<p>Teste di serie: prima contro ultima, seconda contro penultima.</p>}</>}
    <div className="modal-actions"><button className="secondary" onClick={onClose}>Annulla</button><button className="primary" disabled={!valid||busy} onClick={()=>void submit()}>{busy?'Creazione…':'Genera fase finale'}</button></div></section>;
}

function SwissCreate({onClose,onCreated}:{onClose:()=>void;onCreated:(id:string)=>void}){
  const [players,setPlayers]=useState<Player[]>([]);const [selected,setSelected]=useState<string[]>([]);const [guests,setGuests]=useState('');const [name,setName]=useState('');const [mode,setMode]=useState<'fisso'|'illimitati'>('fisso');const [maxRounds,setMaxRounds]=useState(5);const [useNames,setUseNames]=useState(false);const [overrides,setOverrides]=useState<Record<string,{team:string;potential:number}>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const requestId=useRef(crypto.randomUUID());
  const [badgesByKey,setBadgesByKey]=useState<BadgeMap>({});const [badgeEditorOpen,setBadgeEditorOpen]=useState(false);const [badgeTarget,setBadgeTarget]=useState('');
  useEffect(()=>{api<Player[]>('/players').then(setPlayers).catch(e=>setError(err(e)));},[]);
  const entries=[...players.filter(p=>selected.includes(p.id)).map(p=>({key:p.id,source_id:p.id,name:p.name,team:overrides[p.id]?.team??(useNames?p.name:p.team),potential:overrides[p.id]?.potential??(Number(p.potential)||4),guest:false})),...guests.split('\n').map(s=>s.trim()).filter(Boolean).map((value,i)=>({key:`guest:${i}`,source_id:null,name:value,team:overrides[`guest:${i}`]?.team??(useNames?value:''),potential:overrides[`guest:${i}`]?.potential??4,guest:true}))];
  const labels=entries.map(e=>e.team.trim()?`${e.team.trim()} - ${e.name}`:e.name);const valid=name.trim().length>0&&entries.length>=3&&entries.length<=64&&new Set(labels.map(x=>x.toLocaleLowerCase())).size===labels.length&&entries.every(e=>e.potential>=1&&e.potential<=10);
  const badges=Object.fromEntries(entries.flatMap((entry,i)=>{const badge=badgesByKey[entry.key]??players.find(p=>p.id===entry.source_id)?.badge;return badge?[[labels[i],badge]]:[];})) as BadgeMap;
  async function submit(){setBusy(true);setError('');try{const data=await api<Competition>('/swiss','POST',{name:name.trim(),mode,max_rounds:maxRounds,participants:entries.map(({source_id,name,team,potential,guest})=>({source_id,name,team,potential,guest})),badges,request_id:requestId.current});onCreated(data.id);}catch(e){setError(err(e));}finally{setBusy(false);}}
  return <section className="results-card competition-create"><div className="section-heading"><div><h2>✚ Nuovo torneo svizzero</h2><p>Seleziona giocatori reali o aggiungi ospiti.</p></div></div>{error&&<div className="alert error">{error}</div>}<div className="creation-options"><label>Nome torneo<input value={name} onChange={e=>setName(e.target.value)} placeholder="Torneo Subbuteo Svizzero - …"/></label><label>Turni<select value={mode} onChange={e=>setMode(e.target.value as 'fisso'|'illimitati')}><option value="fisso">Numero fisso</option><option value="illimitati">Fino a esaurimento incroci</option></select></label>{mode==='fisso'&&<label>Numero di turni<input type="number" min={1} max={50} value={maxRounds} onChange={e=>setMaxRounds(Number(e.target.value))}/></label>}</div><label className="checkbox"><input type="checkbox" checked={useNames} onChange={e=>setUseNames(e.target.checked)}/>Usa il nome giocatore anche come squadra</label><PlayerMultiSelect players={players} selected={selected} onChange={setSelected}/><div className="player-picker">{players.map(p=><label className="checkbox" key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,p.id]:current.filter(x=>x!==p.id))}/>{p.name} · {p.team}</label>)}</div><label>Giocatori ospiti, uno per riga<textarea value={guests} onChange={e=>setGuests(e.target.value)} placeholder="Nome ospite"/></label><div className="participant-editor">{entries.map(e=><div className="participant-row" key={e.key}><strong>{e.name}{e.guest&&<small> ospite</small>}</strong><label>Squadra<input value={e.team} onChange={event=>setOverrides(o=>({...o,[e.key]:{team:event.target.value,potential:e.potential}}))}/></label><label>Potenziale<input type="number" min={1} max={10} value={e.potential} onChange={event=>setOverrides(o=>({...o,[e.key]:{team:e.team,potential:Number(event.target.value)}}))}/></label><button type="button" className="secondary compact" onClick={()=>{setBadgeTarget(e.team.trim()?`${e.team.trim()} - ${e.name}`:e.name);setBadgeEditorOpen(true);}}>🛡️ Scegli stemma</button></div>)}</div><button type="button" className="secondary" onClick={()=>setBadgeEditorOpen(true)}>🛡️ Immagini per la vista Premium</button><div className="modal-actions"><button className="secondary" onClick={onClose}>Annulla</button><button className="primary" disabled={!valid||busy} onClick={()=>void submit()}>{busy?'Creazione…':'Genera primo turno'}</button></div>{badgeEditorOpen&&<BadgeEditor participants={labels} badges={badges} busy={busy} initialSelected={badgeTarget} error={error} onClose={()=>setBadgeEditorOpen(false)} onSave={async selectedBadges=>{setBadgesByKey(Object.fromEntries(entries.flatMap((entry,i)=>selectedBadges[labels[i]]?[[entry.key,selectedBadges[labels[i]]]]:[])));setBadgeEditorOpen(false);}}/>}</section>;
}

function CompetitionView({kind,data:t,writable,user,onBack,onSaved,onDirty,onLegacy}:{kind:Kind;data:Competition;writable:boolean;user:User;onBack:()=>void;onSaved:(t:Competition)=>void;onDirty:(v:boolean)=>void;onLegacy:()=>void}){
  const storageKey=`tigullio-drafts:${user.id}:${t.id}`;const [drafts,setDrafts]=useState<Record<number,Draft>>(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'{}').drafts||{};}catch{return {};}});const [draftVersion,setDraftVersion]=useState(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'{}').version||t.version;}catch{return t.version;}});
  const preferenceKey=`tigullio-view:${user.id}`;
  const [round,setRound]=useState(t.active_round);const [all,setAll]=useState(false);const [status,setStatus]=useState('all');const [player,setPlayer]=useState('');const [tab,setTab]=useState('matches');const [settingsOpen,setSettingsOpen]=useState(false);const [nameMode,setNameMode]=useState(()=>{try{return JSON.parse(localStorage.getItem(preferenceKey)||'{}').nameMode||'teams';}catch{return 'teams';}});const [viewMode,setViewMode]=useState<ViewMode>(()=>{try{const value=JSON.parse(localStorage.getItem(preferenceKey)||'{}').viewMode;return ['compact','premium','standard'].includes(value)?value:'compact';}catch{return 'compact';}});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [celebrating,setCelebrating]=useState(false);const [badgeEditorOpen,setBadgeEditorOpen]=useState(false);const victoryAudio=useRef<HTMLAudioElement>(null);
  const base=kind==='finali'?'/finals':'/swiss';const dirty=Object.keys(drafts).length>0;const conflict=dirty&&draftVersion!==t.version;const rounds=[...new Set(t.matches.map(r=>r.round))].sort((a,b)=>a-b);const shownRound=rounds.includes(round)?round:t.active_round;const players=[...new Set(t.matches.flatMap(r=>[r.home,r.away]))].sort();const rows=t.matches.filter(r=>all?(status==='all'||(status==='played')===r.valid)&&(!player||r.home===player||r.away===player):r.round===shownRound);
  useEffect(()=>{onDirty(dirty);try{if(dirty)localStorage.setItem(storageKey,JSON.stringify({drafts,version:draftVersion}));else localStorage.removeItem(storageKey);}catch{}},[drafts,draftVersion]);
  useEffect(()=>{try{localStorage.setItem(preferenceKey,JSON.stringify({nameMode,viewMode}));}catch{}},[preferenceKey,nameMode,viewMode]);
  useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
  function change(row:Match,patch:Partial<Draft>){if(!dirty)setDraftVersion(t.version);setDrafts(old=>{const next={...old};next[row.index]={...(old[row.index]||{home:row.home_goals,away:row.away_goals,valid:row.valid}),...patch};if(next[row.index].home===row.home_goals&&next[row.index].away===row.away_goals&&next[row.index].valid===row.valid)delete next[row.index];return next;});}
  async function action(endpoint:string){setBusy(true);setError('');setNotice('');try{const data=await api<Competition>(`${base}/${t.id}/${endpoint}`,'POST',{version:t.version});onSaved(data);setRound(data.active_round);setNotice(data.finished?'🏆 Torneo concluso!':'Nuovo turno pronto.');}catch(e){setError(err(e));}finally{setBusy(false);}}
  async function save(){setBusy(true);setError('');try{const data=await api<Competition>(`${base}/${t.id}/results`,'PATCH',{version:draftVersion,results:Object.entries(drafts).map(([index,value])=>({index:Number(index),...value}))});onSaved(data);setDrafts({});setDraftVersion(data.version);setNotice('Risultati salvati.');}catch(e){setError(err(e));}finally{setBusy(false);}}
  async function saveBadges(badges:BadgeMap){setBusy(true);setError('');try{const data=await api<Competition>(`${base}/${t.id}/badges`,'PATCH',{version:t.version,badges});onSaved(data);setBadgeEditorOpen(false);setNotice('Immagini Premium salvate.');}catch(e){setError(err(e));}finally{setBusy(false);}}
  const active=t.matches.filter(r=>r.round===t.active_round);const canAdvance=active.length>0&&active.every(r=>drafts[r.index]?.valid??r.valid)&&!dirty;
  return <><button className="back" onClick={onBack}><ArrowLeft size={16}/>Tutti i tornei</button><section className="page-heading tournament-heading arena-hero"><div className="arena-copy"><div className="eyebrow"><span className="arena-live-dot"/> TIGULLIO MATCH CENTER · {kind==='finali'?'FASI FINALI':'SVIZZERO'}</div><h1>{title(t.name)}</h1><p>{kind==='finali'?'Un turno alla volta, fino alla finale.':'Incroci nuovi, classifica viva.'}</p><div className="arena-facts"><span><strong>{t.matches.filter(r=>r.valid).length}<em>/{t.matches.length}</em></strong>partite validate</span><span><strong>{rounds.length}</strong>turni</span>{kind==='svizzero'&&<span><strong>{t.standings?.length||0}</strong>partecipanti</span>}</div></div><div className="arena-visual" aria-hidden="true"><div className="arena-field"><i className="arena-midline"/><i className="arena-circle"/><i className="arena-box arena-box-top"/><i className="arena-box arena-box-bottom"/><i className="arena-disc disc-one"/><i className="arena-disc disc-two"/><i className="arena-ball"/></div></div><span className={'badge '+(t.finished?'done':'')}>{t.finished?'🏆 Concluso':'● In corso'}</span></section>
    {error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}</div>}{conflict&&<div className="alert error">Il torneo è cambiato: conserva le bozze e ricarica prima di salvare.</div>}
    {t.finished&&<section className="victory-panel"><div><Trophy/><strong>{celebrating?'🎉 Campione Tigullio!':'🏆 Torneo concluso'}</strong><span>{kind==='finali'?t.winner:t.standings?.[0]?.Squadra}</span></div><button type="button" className="victory-button" onClick={()=>{setCelebrating(true);victoryAudio.current?.pause();if(victoryAudio.current)victoryAudio.current.currentTime=0;void victoryAudio.current?.play().catch(()=>{});}}>🏆 Celebra vincitore 🎉</button>{celebrating&&<div className="victory-confetti" aria-hidden="true">🎈 🎊 🏆 🎊 🎈</div>}<audio ref={victoryAudio} src="/wearethechamp.mp3" preload="none"/></section>}
    <div className="tournament-toolbar"><div className="tabs"><button className={tab==='matches'?'active':''} onClick={()=>setTab('matches')}>⚽ Partite</button>{kind==='svizzero'&&<button className={tab==='standings'?'active':''} onClick={()=>setTab('standings')}>🏆 Classifica</button>}{kind==='finali'&&<button className={tab==='bracket'?'active':''} onClick={()=>setTab('bracket')}>⚡ Tabellone</button>}</div><div className="toolbar-actions"><button className="secondary compact share-link" onClick={async()=>{const link=new URL(tournamentPath(t.name,kind),window.location.origin).toString();try{await navigator.clipboard.writeText(link);setNotice('Link diretto copiato.');}catch{window.prompt('Copia il link',link);}}}><Copy size={16}/>Copia link</button><button className="icon-button" title="Ricarica" onClick={()=>{if(!dirty)api<Competition>(`${base}/${t.id}`).then(onSaved).catch(e=>setError(err(e)));}}><RefreshCw size={16}/></button><a className="secondary compact" href={`/api${base}/${t.id}/export.pdf`}><Download size={16}/>PDF</a></div></div>
    {tab==='matches'&&<><section className={'match-settings'+(settingsOpen?' open':'')}><button type="button" className="settings-toggle" aria-expanded={settingsOpen} onClick={()=>setSettingsOpen(value=>!value)}>⚙️ <span>Impostazioni</span><ChevronDown size={18}/></button>{settingsOpen&&<div className="settings-content"><div className="settings-section"><div className="settings-section-head"><strong>🎯 Filtri e nomi</strong><div className="segmented"><button className={!all?'active':''} onClick={()=>setAll(false)}>Per turno</button><button className={all?'active':''} onClick={()=>setAll(true)}>Tutte le partite</button></div></div><div className="filter-grid"><label>Formato nomi<select value={nameMode} onChange={e=>setNameMode(e.target.value)}><option value="complete">Squadra e giocatore</option><option value="teams">Solo squadre</option><option value="players">Solo giocatori</option></select></label>{all&&<><label>Stato<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tutte</option><option value="played">Giocate</option><option value="unplayed">Da giocare</option></select></label><label>Giocatore<select value={player} onChange={e=>setPlayer(e.target.value)}><option value="">Tutti</option>{players.map(p=><option key={p}>{p}</option>)}</select></label></>}</div></div><div className="settings-section view-switcher"><span>👁️ Vista incontri</span><div className="segmented" role="group" aria-label="Vista incontri">{(['compact','premium','standard'] as ViewMode[]).map(mode=><button key={mode} className={viewMode===mode?'active':''} aria-pressed={viewMode===mode} onClick={()=>setViewMode(mode)}>{mode==='compact'?'📋 Compact':mode==='premium'?'✨ Premium':'📰 Standard'}</button>)}</div>{viewMode==='premium'&&writable&&<button type="button" className="secondary compact" disabled={dirty||busy} onClick={()=>setBadgeEditorOpen(true)}>🛡️ Bandiere e stemmi</button>}</div></div>}</section>
      {!all&&<div className="round-selector"><div className="round-selector-head"><span>📅 {kind==='finali'?t.matches.find(r=>r.round===shownRound)?.round_name||`Turno ${shownRound}`:`Turno ${shownRound}`} <small>di {rounds.length}</small></span><div><button aria-label="Turno precedente" disabled={rounds.indexOf(shownRound)<=0} onClick={()=>setRound(rounds[rounds.indexOf(shownRound)-1])}><ArrowLeft size={17}/></button><button aria-label="Turno successivo" disabled={rounds.indexOf(shownRound)>=rounds.length-1} onClick={()=>setRound(rounds[rounds.indexOf(shownRound)+1])}><ArrowRight size={17}/></button></div></div><div className="round-track">{rounds.map(n=><button key={n} className={n===shownRound?'active':''} onClick={()=>setRound(n)}>T{n}</button>)}</div></div>}
      <section className="results-card tournament-results"><div className="results-heading"><h3>{all?`⚽ Partite filtrate (${rows.length})`:kind==='finali'?`⚡ ${t.matches.find(r=>r.round===shownRound)?.round_name||`Turno ${shownRound}`}`:`⚽ Turno ${shownRound}`}</h3><span>{rows.filter(r=>drafts[r.index]?.valid??r.valid).length}/{rows.length} validate</span></div><div className={`matches ${viewMode}`} key={all?'all':shownRound}>{rows.map((row,index)=>{const value=drafts[row.index]||{home:row.home_goals,away:row.away_goals,valid:row.valid};const enabled=writable&&!t.finished&&row.round===t.active_round&&!busy;return <div className={'match-row '+(drafts[row.index]?'edited':'')} style={{'--match-order':Math.min(index,12)} as CSSProperties} key={row.index}><span className="match-meta">{all?`T${row.round} · `:''}PARTITA {String(index+1).padStart(2,'0')}</span><span className="team home" title={row.home}>{all&&<small className="compact-day">T{row.round}</small>}<span className="team-mark"><TeamMark name={row.home} badge={viewMode==='premium'?t.badges?.[row.home]:undefined}/></span><span>{format(row.home,nameMode)}</span></span><div className="score"><input type="number" min={0} max={20} aria-label={`Gol casa ${row.home}`} value={value.home} disabled={!enabled} onChange={e=>change(row,{home:Number(e.target.value)})}/><span>:</span><input type="number" min={0} max={20} aria-label={`Gol ospite ${row.away}`} value={value.away} disabled={!enabled} onChange={e=>change(row,{away:Number(e.target.value)})}/></div><span className="team away" title={row.away}><span>{format(row.away,nameMode)}</span><span className="team-mark alt"><TeamMark name={row.away} badge={viewMode==='premium'?t.badges?.[row.away]:undefined}/></span></span><label className={'validate '+(value.valid?'valid':'')}><input type="checkbox" checked={value.valid} disabled={!enabled} onChange={e=>change(row,{valid:e.target.checked})}/>{value.valid?'✓ Validata':'○ Da validare'}</label></div>;})}{!rows.length&&<div className="empty">Nessuna partita corrisponde ai filtri.</div>}</div></section></>}
    {tab==='standings'&&<section className="results-card"><div className="results-heading"><h3>🏆 Classifica</h3></div><div className="table-scroll"><table><thead><tr><th>#</th><th>Squadra / giocatore</th><th>Pt</th><th>G</th><th>V</th><th>N</th><th>P</th><th>GF</th><th>GS</th><th>DR</th></tr></thead><tbody>{t.standings?.map((r,i)=><tr key={r.Squadra}><td>{i+1}</td><td><span className="standing-identity">{viewMode==='premium'&&<span className="team-mark"><TeamMark name={r.Squadra} badge={t.badges?.[r.Squadra]}/></span>}{format(r.Squadra,nameMode)}</span></td><td className="points">{r.Punti}</td><td>{r.G}</td><td>{r.V}</td><td>{r.N}</td><td>{r.P}</td><td>{r.GF}</td><td>{r.GS}</td><td>{r.DR}</td></tr>)}</tbody></table></div>{!!t.byes?.length&&<p className="results-note">💤 Riposi: {t.byes.map(b=>`${format(b.team,nameMode)} (T${b.round})`).join(' · ')}</p>}</section>}
    {tab==='bracket'&&<section className="results-card competition-bracket"><h3>⚡ Percorso verso la finale</h3>{rounds.map(n=><div key={n}><h4>{t.matches.find(r=>r.round===n)?.round_name||`Turno ${n}`}</h4>{t.matches.filter(r=>r.round===n).map(r=><p key={r.index}>{viewMode==='premium'&&<span className="team-mark"><TeamMark name={r.home} badge={t.badges?.[r.home]}/></span>}{format(r.home,nameMode)} <strong>{r.valid?`${r.home_goals} : ${r.away_goals}`:'— : —'}</strong> {format(r.away,nameMode)} {r.winner&&<span>🏆 {format(r.winner,nameMode)}</span>}</p>)}</div>)}</section>}
    {dirty&&<div className="savebar"><span>{Object.keys(drafts).length} partite con modifiche non salvate</span><button className="primary" disabled={!writable||busy||conflict} onClick={()=>void save()}><Save size={17}/>Salva risultati</button></div>}
    {!t.finished&&writable&&canAdvance&&<div className="completion"><Trophy/><div><h3>{kind==='finali'&&active.length===1?'La finale è pronta per essere conclusa':'Turno completato'}</h3><p>{kind==='finali'?'I vincitori avanzano nel tabellone.':'Genera gli accoppiamenti del turno successivo, oppure concludi.'}</p></div><button className="primary" disabled={busy} onClick={()=>void action('advance')}>{kind==='finali'&&active.length===1?'Concludi finale':'Avanza al prossimo turno'}</button>{kind==='svizzero'&&<button className="secondary" disabled={busy} onClick={()=>{if(window.confirm('Concludere ora il torneo svizzero?'))void action('finish');}}>Concludi torneo</button>}</div>}
    {badgeEditorOpen&&<BadgeEditor participants={players} badges={t.badges||{}} busy={busy} error={error} onClose={()=>setBadgeEditorOpen(false)} onSave={saveBadges}/>}
    <div className="legacy-note"><span>La versione classica resta disponibile durante la migrazione.</span><button className="text-button" onClick={onLegacy}>Apri versione classica<ArrowUpRight size={15}/></button></div>
  </>;
}
